### PR TITLE
Wiki Plugin

### PR DESCRIPTION
**Pull request by amitkumarj441**
Added Wikipedia Plugin for #62

### CODE REVIEW

**Comment by CapacitorSet** [comment]
The plugin as it is now is not suitable for usage in Telegram-Bot-Node. Refer to the docs (eg. [`docs/Plugins.md`](https://github.com/crisbal/Telegram-Bot-Node/blob/es6/docs/Plugins.md)) for help on how plugins must be structured; see [`src/plugins/ImageSearch.js`](https://github.com/crisbal/Telegram-Bot-Node/blob/es6/src/plugins/ImageSearch.js) for a sample plugin.

**Comment by amitkumarj441** [comment]
Okay @CapacitorSet ! I'll check it and will structure in the way as given in `Plugins.md`

**Comment by amitkumarj441** [comment]
@CapacitorSet Now, I structured my code according to the given doc. Please review my PR.

**Comment by CapacitorSet** [comment]
This PR is a complete trainwreck. Please develop on your fork, _test your changes_ (the code didn't even compile), and submit a PR when you're ready and your code is up to Telegram-Bot-Node's standards.

Edit: try running the bot yourself and make sure that the plugin works with the bot. As it is now, it doesn't work, because it lacks an onText property, for example.

**Pull request closed without merging**
